### ISSUE TITLE
Write a tutorial

### ISSUE THREAD

**Issue by mjallday** [balanced/billy#13]
I just found this sweet recurring billing software called Billy. It looks totally awesome but I don't know how to use it. It sure would be cool if there was a tutorial that showed me how :)

**Comment by 40** [comment]
BUMP.

**Comment by fangpenlin** [comment]
@40 

I just wrote a rough tutorial for billy, you can read it at http://balancedbilly.readthedocs.org/en/latest/index.html

**Comment by 40** [comment]
Thank you.
