### ISSUE TITLE
Keep tests in good style

### ISSUE THREAD

**Issue by fangpenlin** [balanced/billy#22]
I had a glance on the test code, I think it needs some clean up. For example, import statements should not be put in the module level. In cases, some modules are missing, other tests can continue.

For example, this

```
import unittest

class TestSometing(unittest.TestCase):

    def test_xxx(self):
        import module1
        from my_module import do_some_thing
        do_some_thing()
        # ...
```

is better than

```
import unittest

import module1
from my_module import do_some_thing

class TestSometing(unittest.TestCase):

    def test_xxx(self):
        do_some_thing()
        # ...
```

For more guideline, please reference to this article:

http://docs.pylonsproject.org/en/latest/community/testing.html

It is Pyramid testing guideline, very neat practices to follow. Pyramid have 100% test coverage, these guys are proud of it.

**Comment by mjallday** [comment]
We generally follow pep guidelines for python coding - http://www.python.org/dev/peps/pep-0008/#imports - in this case the format is:
1. standard library imports
2. related third party imports
3. local application/library specific imports

It's a decent opinion but if a module is missing I (hope) it would never be checked in so it wouldn't break. We'll keep the current formatting since it's internally consistent across all our code bases :)

**Comment by fangpenlin** [comment]
Actually, when a module is missing, surely tests will be broken, it only matters where and how it breaks it. For module level imports, the whole test module is broken. For function level imports, only specific cases are broken. 

For instance:

``` python
import unittest

import foobar.moda
import foobar.modb

class TestFooBar(unittest.TestCase):
    def test_case_a(self):
        foobar.moda.func1()

    def test_case_b(self):
        foobar.modb.func3()
```

In above code, the whole testing module will raise ImportError, no test cases will be executed. Surely the test is broken, but it breaks everything. You cannot know details about how it breaks thing. When it is in function level

``` python
import unittest

class TestFooBar(unittest.TestCase):
    def make_func1(self):
        from foobar.moda import func1
        return 

    def make_func3(self):
        from foobar.modb import func3
        return 

    def test_case_a(self):
        func1 = self.make_func1()
        func1()

    def test_case_b(self):
        func3 = self.make_func3()
        func3()
```

In this case, when a module is missing, still, cases will be broken, but you can know exactly which cases are broken. This brings a lots of benefit. For example, you want to upgrade the foobar module to the latest one, but the API is changed, module name is changed as well. In that case, module import will break everything. You have no idea what kind of impact that upgrading will bring. But for function level imports, you can know exactly which tests are broken by these module name changes.

And for the formatting, I also keep pep8 style in my own code base, however, I see testing code as an exception. Testing servers a different purpose than common code, surely it should follow a different guideline.

You can read the testing code of pyramid to see how they do it

https://github.com/Pylons/pyramid/tree/master/pyramid/tests
