### ISSUE TITLE
Import billy project module in either absolute or relative manner

### ISSUE THREAD

**Issue by fangpenlin** [balanced/billy#23]
It is better to import project modules in a certain package. For example, code like this

```
from models.base import Base, RelativeDelta
from models.groups import Group
from utils.generic import uuid_factory
```

Should rewrite in 

```
from billy.models.base import Base, RelativeDelta
from billy.models.groups import Group
from billy.utils.generic import uuid_factory
```

style. Otherwise, you cannot understand which one is from your own project, which are from other third-party packages. Also, it will be error prone in certain situation. If it is a relative import, for example

```
+ billy 
    + models
        - module_a.py
        - module_b.py
    - module_c.py
```

In module_a.py, you can import module_b.py and module_c.py like this

```
from . import module_b
from .. import module_c
```

But you should notice that, when you use a relative manner, the module should be imported in a relative manner as well to import correctly. You cannot execute 

```
python module_a.py
```

and expect it works. It would work when it is

```
python -m billy.models.module_a
```

It is executed (or imported) in a relative manner, then it can find parent module then the relative ones.

So, in most cases, absolute import style is recommended.

**Comment by mjallday** [comment]
+1 on not using relative imports, they always bite me during refactoring.
