### ISSUE TITLE
How can I run tests?

### ISSUE THREAD

**Issue by fangpenlin** [balanced/billy#31]
@pnegahdar 

I am trying to work on billy project, however, I cannot get tests work. How can I run them correctly?

I tried `nosetests` on the `mater` branch, and basically everything failed

```
$ nosetests

EEEEEEEEEEEEEEEE
======================================================================
ERROR: Failure: InvalidRequestError (Table 'charge_subscription' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.)
----------------------------------------------------------------------
    (... omit ...)
----------------------------------------------------------------------
Ran 16 tests in 0.012s

FAILED (errors=16)
```

The complete dump: https://gist.github.com/victorlin/6204313

It appears that something goes wrong with import issue and table declarations. So, I tried my import fixed branch, and I get other tons of error

```
EEEEEEEEEEEEEEE
======================================================================
ERROR: Failure: ImportError (cannot import name sample_customer_2)
----------------------------------------------------------------------
    ( ... omit ...)
----------------------------------------------------------------------
Ran 15 tests in 0.563s

FAILED (errors=15)
```

The complete dump: https://gist.github.com/victorlin/6204321

None of tests passed, did I miss something? How do you run tests usually?

**Comment by pnegahdar** [comment]
Only the new model tests (they arent unit yet, just basic model test) are currently not broken. I just redid all the models so they're much cleaner and will have to soon redo api parts to use the new model interface.  The api is currently compelely broken. The models tests should be run using

nosetests billy/tests/test_models/ and they should pass safely (I need to add transactional testing back soon)

We should schedule sometime to chat to coordinate our effors. There are still big things needed to be done, heres my top 4:

1) Update the api to use the new dashboard
2) Most api tests should work, but some probably need to be rewritten
3) In depth unit-testing of the models 
4) Start some sort of documentation process.

**Comment by fangpenlin** [comment]
Yeah, I think we definitely should figure a way to work these out together. However, I have some points want to list here to remind us.

#### Write expressive commit messages

I saw there are many commit messages are like 
- yo
- gota go
- time to eat

Or anything like that. If one is doing this in his private project, nobody would care. However, we are developing a public facing open source project. Me and other developers certainly cannot understand what kind of change these commits are for. As a result, all developers need to read into these commits line by line. This is costly.

If you are doing a refactorying, then write "refactorying", no "yo" please. That would bring negative impression to anyone who have a glance on it, they will think you are not professional. For your own good, please stop using "yo".

When you have to do the commit for safety reason anyway, you can clean your dirty commits before merge with `git rebase -i` command. You can reference to the article I wrote here

https://github.com/balanced/balanced-dashboard/issues/461

#### Keep the master branch stable

I saw you mentioned

> +1, @victorlin can you branch into victor, merge into develop (ill branch into parham, merge into develop as well) and then we'll do a periodic merge into master

The point of keeping develop branch apart from the master is that people want to have a stable branch to work on. But so far, I see the master branch is very broken. So, that is meaningless to keep a develop branch apart from master when the master is also broken.

I think the first priority here is to bring the broken master back to stable. Stop adding any new features even more, maybe we should remove some non-core features, try to reach a stable state with minimum features and add other features back later. I see what we are doing now is trying to drag all tons of stuff around and seek for a stable state. This is not very productive. IMHO, we should put some heavy stuff down, look around for a good place to live, then migrate our old stuff to our nice new location. This is the correct way we should go.

Here I quote one week data from GitHub:

> 2 authors have pushed 38 commits to all branches, excluding merges. On master, 106 files have changed and there have been 4,410 additions and 4,173 deletions.

Nobody can contribute on this project as if it is dynamic like this. Surely we should change the approach.

So again, we should see this in a team player role and open source developer perspective.

#### Find a new approach for developing collaboratively

Another serious issue we had here is that we don't have functional tests running against the project. As you said we should merge develop branch to master periodically, however, that's when we have some tests running there, we only merge develop branch to master when the test pass. So, another priority task to do is to make tests easy to run, this is why I am bringing SQLite.

After we bring this project back to the track (with a stable master), a new approach should be used, but still, I don't see develop-master branch model is a good idea with this small team size and text based communication is required. Instead, I think what we are doing on the dashboard project is pretty good. We open new issues for new problems, enhancements and bugfixes. And create branches for corresponding issues, once finished, we merge them back to the master. 

This is the very first workable approach came to my mind, if you have any idea, you can propose it and we can talk about it.

**Comment by pnegahdar** [comment]
Relax my man. One overarching theme here is that Billy isn't at a stage yet where other developers are going to contribute. As you (hopefully) can tell by the 8k LOC change in 1 week. Concerns like master vs develop, setup.py configuration, import configs that get fixed with a simple refactor etc are all premature if you keep this in mind. Right now the biggest concern should be getting something good and working (move fast and break things). Until we have a stable interface/api tests are going to break and it shouldn't be a concern. @mahmoudimus wanted me to push to master event at unstable points so the public facing page shows progress (much more of a concern at this point than co-contributing). I'm no longer working on billy (after I get the api and test stable early this week). So I suggest you wait until I get that done, ill merge master, rebase and then you  can come up with a good git strategy for you and the team going forward.

**Comment by fangpenlin** [comment]
I am sorry, I know I am a little bit picky on software development practices, but that's because it is important to do the good practice at the very first time when it is possible and not difficult to do. It's all about cost and quality. 

There are some stories happened when I am working with my former employer, I can share some with you

#### Story 1, a developer committed code like this

``` python
def authenticate_staff(user_id):
    return True
    # remain code for doing the check
```

This is a function for checking whether is a user staff. The developer committed this kind of code for development test reason by mistake, and it leads our staff dashboard been exposed for a month. The developer is very talent (he went to Google afterward), so why is he making this kind of mistake? Because there is no test running against the code before deployment (and maybe there are also no tests for important function like that). I don't see this is his fault, this is the fault of the whole team - bad practice leads the bad result.

#### Story 2, I was assigned to do a straightforward task, but it is god damn hard to do it right.

I recall what I have to do is to make an web UI for user to update some fields in database, and reflect that on the website. I did it but I notice that new data is not reflected on the web. It costs lots of my time to trace down the issue, and eventually found that there are code for caching everywhere, the cache is not flushed, so the new data is not displayed. There is no consistent way they do cache, just cache here and cache there, as a result, the code is god damn difficult to modify even it is a straightforward task.

I am not here to blame you. I can probably keep silence, but I see your potential, this is why I spend my time on typing all of this. I just want to share my experience and some of my thoughts, I am sorry if this let you feel a little bit offensive.

As we know the cost for developing software is actually only 20% of the overall cost. There are 80% goes into maintenance. So, when a software is badly built with very cheap price, maybe it would be more costly when people try to maintain it. There is a term `technical debt`, when one is doing quick and dirty hack on the code to achieve a short term goal, he is actually raising `technical debt`. Just like real debt, it doesn't come for free, people should pay interest for the debt. 

For example, one writes some

```
hard to read code
```

when the author read this himself, or others do, they actually pay the interest (extra effort) for the debt he raised.

Code without tests also can be seen as debt. Say one has ten features, but no tests for them, then every time you modify the code, you should check these ten features are not broken, this is the interest you should pay. When more and more features are added, the interest cost will raise. Surely he can just ignore that, then some of features might be broken without anyone knows that (just like what happened in the story 1).

However, debts are not that evil if you know when to raise them. Sometimes raising debt can be good, such as
- run once and throw away project
- reaching a short term goal for good reason

Good developers know when to raise them and how much they will raise by doing this. Also, they can keep the debt as low as possible with good practice. Keeping good practice is definitely not premature. Avoiding error-prone practice at very first time is also not premature. 

I can actually write a full page article about good practice and technical debt (maybe I will), but I think this is pretty much it. Hopefully this could be helpful. Good luck, cheers.

**Comment by pnegahdar** [comment]
I guess its depends on programming style. I believe, especially at this stage, that a refectory process is fine, and the the technical debt you speak of is no where this big a deal as you make it. However, I think we'd both agree that if time loss is really an issue, pull requests work substantially better and more efficiently than unnecessarily long writes ups as PRs solve the issue and inherently document the problems.

**Comment by fangpenlin** [comment]
A whole project wise import issue is actually the technical debt. As you see that is error-prone and indeed it causes many problems when I tried to run the tests. If you are building a few scripts project that's totally fine to do what you are doing here. However, this is a small to middle size project, do import like that you have no idea when you will got bite. 

Also, the point is, omitting the `billy` namespace prefix for import statements actually brings no benefit but only harm, what do you get from not doing that? save few seconds of typing? This surly can be done without any pain at very first time the project is created (with a setup.py script and everything should be there). 

I just feel this kind of problem should not be there under months development. Fixing hounder lines of import statements just drives me crazy a little bit. You know, that's not pleasant, api, which api? models? which models? third party or from our package? (when pep8 is not followed). which package it is from? Run it, and ouch, more import errors, where are them? which one I missed?  

But anyway, I know you are not expecting other contributors, so, sorry, I am not blaming.

**Comment by fangpenlin** [comment]
I think over this again, I was over reaching. I apologize. I just want to get start work on this project as soon as possible. Sorry for that.

**Comment by pnegahdar** [comment]
Na man, its cool you're raising very valid points. The issue I'm having with this is perspective. For example, the billy prefix is absolutely correct and it was the first way I did it ( https://github.com/balanced/billy/commit/20439ca05a592fb8a8dfdcfc08d2467a847cd931 ), however, I decided to experiment on the potential of distributing billy as a 3 distinct packages and made the switch. Since I was the only one building on it it wasn't really a concern I decided to move forward without splitting the packages and created a todo to fix the import structure back: https://github.com/balanced/billy#major-todos What you're treating as a lack of understanding of how namespacing works, is actually a development cycle issue. I wasn't even notified that you are pairing on billy, or I would have made the necessary modifications to the dev strategy so you can comfortably work on it. Anyway hope theres no gripes on this and I do value and welcome your insight.
