### ISSUE TITLE
How to deal database failure with Balanced API calls?

### ISSUE THREAD

**Issue by fangpenlin** [balanced/billy#34]
I would like to ask a question about how can I deal with database transaction failure with Balanced API calls?

For example, here I am processing a single transaction generated from a subscription

``` python
# create a transaction record in local database
tid = create_transaction(
    amount=100,
    payment_uri='/v1/credit_card/xxx'
)

# try to debit with balanced
transaction = get_transaction(tid)
debit_id = balanced.debit(transaction.payment_uri)

# NOTICE: When following update fails, we have a big trouble, 
# the charging may already done, but we have no idea (no record) about that
# the system will certainly charge the customer again later

# update transaction record, we made a success debit
update_transaction(
    tid=tid,
    status='done',
    debit_id=debit_id,
)
```

This could work fine if everything goes well, however, when a crash or something bad happens during processing this, let's say, the final `update_transaction` is not done successfully. In this case, there is no transaction finish record in the database, billy system will think this transaction is not finish yet, it will try to charge it again when the system goes back online.

The way PayPal deals with this is that user needs to create a profile before they do a transaction like this

``` python

# make sure we won't duplicate transaction
tx = get_transaction()
if tx is not None:
    pp_tx = paypal.get_profile(tx.profile_id)
    if pp_tx.status == 'Paid':
        update_transaction(tx.id, status='done')
        return

profile = paypal.create_profile(...)
create_transaction(profile_id=profile.id)

result = paypal.start_recurring_payment(...)
if result.status == 'Paid':
    update_transaction(tx.id, status='done')
```

As you can see, we can store the profile id in database before we do a real transaction. We can then check before  doing a transaction, to make sure it is not already done.

With balanced, it appears there is only one step to do a transaction. A possible approach to workaround this is to assign a billy generated transaction id to balanced transaction. And we can get previous transaction record back with this id before we try to do a transaction again.

The code would look like this

``` python

# make sure we won't duplicate transaction
tx = get_transaction()
if tx is not None:
    bp_tx = balanced.get_transaction(tx.id)
    if bp_tx.status == 'Paid':
        update_transaction(tx.id, status='done')
        return

tx = create_transaction(...)
balanced.debit(tx.payment_uri)

update_transaction(tx.id, status='done')
```

I am not very familiar with the API, I see there is a `meta` field I can set some of my key-value data to it, but is there a way to retrieve a record by the ID or data I set previously? Or are there other ways to workaround this?

**Comment by mjallday** [comment]
You can use the meta to filter transactions, here's an example:

``` python
In [6]: [d.meta for d in balanced.Debit.query.all()]
Out[6]: 
[{u'transaction': u'bar'},
 {u'transaction': u'foo'},
 {},
 {},
 {},
 {},
 {},
 {u'anykey': u'valuegoeshere', u'facebook.id': u'1234567890'},
 {}]

In [7]: balanced.Debit.query.filter(**{'meta.transaction': 'foo'}).count()
Out[7]: 1
```
