### ISSUE TITLE
Deploy billy to EC2

### ISSUE THREAD

**Issue by fangpenlin** [balanced/billy#44]
Deploy billy to an EC2 instance with Chef. 

@victorlin Write the steps to deploy here later.

**Comment by fangpenlin** [comment]
Okay, I just deployed it to my EC2 instance

http://ec2-54-219-21-15.us-west-1.compute.amazonaws.com

To run integration testing against it, you can run

```
export BILLY_TEST_URL=http://ec2-54-219-21-15.us-west-1.compute.amazonaws.com
export BILLY_TEST_PROCESSOR_KEY=MY_SECRET_KEY_HERE
export BILLY_TEST_MARKETPLACE_URI=/v1/marketplaces/TEST-MP_MY_MARKETPLACE
nosetests billy/tests/integration
```

This could subscribe recurring charging to a new credit card.

![2013-09-03 12 47 42](https://f.cloud.github.com/assets/201615/1070444/1537dc5c-1454-11e3-8688-433a2674da4a.png)

**Comment by fangpenlin** [comment]
### To deploy via Chef

Mainly reference to http://www.captnswing.net/2013/01/from-vagrant-to-ec2-with-knife-solo.html

Clone the billy project

```
git clone https://github.com/victorlin/billy.git
```

clone chef submodule

```
git submodule init
git submodule update
```

cd to the chef folder

```
cd billy/chef
```

install knife solo and ec2 plugins

```
gem install knife-ec2 knife-solo
```

create new ec2 instance, Ubuntu 12.04.1 LTS (Precise Pangolin)

```
export AWS_ACCESS_KEY=YOUR_KEY
export AWS_SECRET_KEY=YOUR_SECRET_KEY
export EC2_REGION=us-west-1
export EC2_AVAILABILITY_ZONE=us-west-1c
knife ec2 server create -S <your_key_pair> -I ami-827252c7 -G default --flavor=m1.large
```

(find corresponding Ubuntu image id here http://cloud-images.ubuntu.com/releases/precise/release-20121218/)

prepare chef

```
knife prepare ec2-xx-xx-xx-xx.us-west-1.compute.amazonaws.com
```

copy and modify the node configuration file

```
cp nodes/ec2.json.example nodes/ec2-xx-xx-xx-xx.us-west-1.compute.amazonaws.com.json
vim nodes/ec2-xx-xx-xx-xx.us-west-1.compute.amazonaws.com.json
```

Okay! Finally, let's cook

```
knife cook ec2-xx-xx-xx-xx.us-west-1.compute.amazonaws.com
```

and run the integration test against it

```
export BILLY_TEST_URL=http://ec2-xx-xx-xx-xx.us-west-1.compute.amazonaws.com
export BILLY_TEST_PROCESSOR_KEY=MY_SECRET_KEY_HERE
export BILLY_TEST_MARKETPLACE_URI=/v1/marketplaces/TEST-MP_MY_MARKETPLACE
cd ..
nosetests billy/tests/integration
```

done!

**Comment by nodesocket** [comment]
Amazing work @victorlin
