### ISSUE TITLE
Limit failure times of a transaction

### ISSUE THREAD

**Issue by fangpenlin** [balanced/billy#45]
The way we process transactions periodically is like this

```
Yield transactions from subscriptions
Process transactions
```

We yield transactions for recurring charging/paying-out/refunding as `transaction` records in the database. The initial status is `INIT`, then we process them. If everything goes well, it should then transit into `DONE` status. However, when something goes wrong, it will go into `RETRYING` status, and we will try to process it again later.

Sometimes, the retrying transactions are just never going to be finished as something is wrong from very beginning, such as wrong balanced API given by user. In this case, it is only wasting time and resource to keep trying these transactions.

So, here I want to limit the maximum retry times for each transactions. After a specific retry times, a transaction shall transit into `FAILED` status.

The whole state transition would look like this:
![billy_transaction_state_diagram](https://f.cloud.github.com/assets/201615/1094010/8f24df2a-16ba-11e3-8899-7404f3770a95.png)

And a note here, as the branch is merged back, I want to keep the development traceable to everybody, so I will stop working on the master branch directly. I will try to create issues and corresponding branch and pull request. I will keep the master as stable as possible, so that everybody can work on it. Also, for pull requests, I think only the ones pass all unit tests and functional tests should be merged. I see youguys have pretty cool testing integration with Github for balanced-dashboard that indicates testing result for each commit. I don't know what it is, but I think we can do the same on billy.

**Comment by mjallday** [comment]
@victorlin you get that for free when you have travis ci integrated. 

agree that we should try and never break master going forward.
