### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by fangpenlin** [balanced/billy#46]
Setup Travis CI (https://travis-ci.org) for billy project

**Comment by mjallday** [comment]
we should include code coverage checks if you can.

**Comment by mjallday** [comment]
This seems to have regressed, reopening.

**Comment by fangpenlin** [comment]
@mjallday regressed?

**Comment by mjallday** [comment]
Hmm, maybe not regressed. Rather, there is no travis-ci icon on the README to show the status of the build. I just turned on travis-ci for billy so we should see builds going through there. - https://travis-ci.org/balanced/billy
