### ISSUE TITLE
Setup beta environment

### ISSUE THREAD

**Issue by fangpenlin** [balanced/billy#54]
@mahmoudimus @mjallday @msherry 

As we know there are customers waiting for billy beta environment. I think we should setup one as soon as possible. Almost everything is ready to go.

We have a Chef repo for deploying it 

https://github.com/victorlin/billy-chef

It is already running on my own EC2 instance mentioned at #44, but I don't think it is a good idea to run Balanced service on my own instance. I think we are using EC2 for deployment aren't we? If we are, we have two options
## 1. I deploy it by my-self

I think I can do the deployment and maintenance by myself, you can setup a account via [AWS Identity and Access Management](http://aws.amazon.com/iam/) with minimum permission to run an EC2 instance, and rest of it is my DIY time.
## 2. Deploy by others

I am not sure how deployment is done usually, maybe someone can deploy it for us.

I am all okay for these two options. See what youguys think.

**Comment by fangpenlin** [comment]
The server is working now at 

http://billing.balancedpayments.com/

However, currently a self-signed cert is using for HTTPS, so you will see a warning if you are connecting to it via HTTPS.

**Comment by nodesocket** [comment]
404 ?

**Comment by fangpenlin** [comment]
@nodesocket There was no view at the root path, I just create a server information page there via #57, this should clear user's doubt.

**Comment by nodesocket** [comment]
@victorlin Cool. Is the documentation live?

**Comment by fangpenlin** [comment]
@nodesocket You can find the document here http://balancedbilly.readthedocs.org/en/latest/index.html

**Comment by fangpenlin** [comment]
Currently, only end-user parts are covered, I will add guides like how to setup the server and so on to it.

**Comment by nodesocket** [comment]
That's some beautiful doc you got there. :) How did you build this?

**Comment by fangpenlin** [comment]
@nodesocket I use [sphinx](http://sphinx-doc.org/) with [Readable theme](https://sphinx-readable-theme.readthedocs.org/en/latest/) (a flask like theme)

To build it, you have to install dependencies first, type

```
pip install -r docs/requirements.txt
```

and 

```
cd docs
make html
```

If you are editing the documents, you want it rebuild automatically, you can use the little script I wrote `autobuild.py`, it monitors file changes in document directory and rebuild automatically for you. Here you run

```
python autobuild.py
```
