### ISSUE TITLE
SSL Cert has expired

### ISSUE THREAD

**Issue by rootedsoftware** [balanced/billy#92]
https://billy.balancedpayments.com
![screen shot 2015-01-13 at 9 07 02 am](https://cloud.githubusercontent.com/assets/3142974/5722670/d3205bfe-9b03-11e4-8fef-e5976a2ad544.png)

**Comment by rootedsoftware** [comment]
This workaround worked for me on Node.js (actually I use meteor, but it runs on Node) http://stackoverflow.com/questions/20433287/node-js-request-cert-has-expired

**Comment by mahmoudimus** [comment]
@c316 thanks for letting me know. somehow billy fell through the cracks from our automated SSL updaters. I'll update now.

**Comment by mahmoudimus** [comment]
@c316 fixed

![image](https://cloud.githubusercontent.com/assets/40820/5726194/5ee373a6-9b0e-11e4-8f8b-2c153d05872b.png)

**Comment by mahmoudimus** [comment]
@c316 can you confirm on your end?

**Comment by rootedsoftware** [comment]
Yes, looks good.
